# Generated by Django 3.0.8 on 2020-07-11 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=20, verbose_name='种类名称')),
                ('isDelete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '商品种类',
                'verbose_name_plural': '商品种类',
                'db_table': 'df_goods_type',
            },
        ),
        migrations.CreateModel(
            name='GoodInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20, verbose_name='商品名称')),
                ('isDelete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('gpic', models.ImageField(upload_to='df_goods', verbose_name='关联图片目录')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品价格')),
                ('gunit', models.CharField(default='500g', max_length=20, verbose_name='商品单位')),
                ('gclick', models.IntegerField(verbose_name='商品点击量')),
                ('gjianjie', models.CharField(max_length=200, verbose_name='商品简介')),
                ('gkucun', models.IntegerField(verbose_name='商品库存')),
                ('gtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.TypeInfo')),
            ],
        ),
    ]
