# Generated by Django 3.0.8 on 2020-07-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodinfo',
            name='gclick',
            field=models.IntegerField(default=0, verbose_name='商品点击量'),
        ),
    ]
