# Generated by Django 3.0.8 on 2020-09-06 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0003_auto_20200905_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodinfo',
            options={'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
        migrations.AlterModelTable(
            name='goodinfo',
            table='df_goods_Good',
        ),
    ]
