# Generated by Django 3.0.8 on 2020-09-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0004_auto_20200906_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodinfo',
            name='gpic',
            field=models.ImageField(upload_to='df_goods', verbose_name='关联图片目录'),
        ),
    ]
