# Generated by Django 3.0.8 on 2020-07-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, verbose_name='用户名')),
                ('upwd', models.CharField(max_length=40, verbose_name='用户密码')),
                ('uemail', models.CharField(max_length=30, verbose_name='邮箱')),
                ('ushou', models.CharField(default='', max_length=200, verbose_name='收货地址')),
                ('uaddress', models.CharField(default='', max_length=200, verbose_name='家庭地址')),
                ('uphone', models.CharField(default='', max_length=20, verbose_name='电话')),
                ('uzipcode', models.CharField(max_length=6, null=True, verbose_name='邮政编码')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'df_user',
            },
        ),
    ]
